name: smart_alarm
description: A smart alarm app for sleep cycles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sensors_plus: ^4.0.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.1.3
  flutter_local_notifications: 14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Vazir
      fonts:
        - asset: fonts/Vazirmatn-Regular.ttf
        - asset: fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: fonts/Vazirmatn-Light.ttf
          weight: 300